export const COLLAPSE_MENU = 'COLLAPSE_MENU';
export const COLLAPSE_TOGGLE = 'COLLAPSE_TOGGLE';
export const FULL_SCREEN = 'FULL_SCREEN';
export const FULL_SCREEN_EXIT = 'FULL_SCREEN_EXIT';
export const CHANGE_LAYOUT = 'CHANGE_LAYOUT';
export const NAV_CONTENT_LEAVE = 'NAV_CONTENT_LEAVE';
export const NAV_COLLAPSE_LEAVE = 'NAV_COLLAPSE_LEAVE';

//AUTH
export const USER_LOADING_START = "USER_LOADING_START";
export const USER_LOADED = "USER_LOADED";
export const USER_LOADING_FAIL = "USER_LOADING_FAIL";
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_ERROR = "LOGOUT_ERROR";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_START = "REGISTER_START";
export const AUTH_ERROR = "AUTH_ERROR";
export const PASSWORD_CHANGE_FAILED = 'PASSWORD_CHANGE_FAILED';
export const PASSWORD_CHANGE_SUCCESS = 'PASSWORD_CHANGE_SUCCESS';
export const PASSWORD_CHANGE_START = 'PASSWORD_CHANGE_START';

//CATEGORIES
export const CATEGORY_LOADING = "CATEGORY_LOADING";
export const CATEGORY_LOADED = "CATEGORY_LOADED";

// ALERTS
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";